### ISSUE TITLE
Enabled dynamic adding/remove of nodes

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#322]
This feature is to provide an easy way for a user to add and remove nodes from the palette without having to restart the runtime.

Design notes are on the [wiki](https://github.com/node-red/node-red/wiki/dynamic-palette)

This top level issue will capture the work-items as they come up.
- [x] For nodes that statically contribute content to the editor (eg, Debug node tab), need to provide an api for adding/removing this content.
- [x] Add runtime support for running npm install/remove (with consideration of bluemix and adding dependencies post-install)
- [ ] Provide an editor-based UI for adding/removing nodes

---
- [x] Provide an runtime api for adding/removing nodes
- [x] Allow the editor to update its palette on notification from the runtime
- [x] Handle removing node(s) that are currently in use. ('handle' means don't allow it)
