### ISSUE TITLE
Subflows

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#418]
A subflow is a set of connected nodes that can be easily referenced and reused within a larger flow.

This issue is an epic to link off to specific work items as they arise.

The design notes are [on the wiki](https://github.com/node-red/node-red/wiki/Design%3A-subflows).

This is being developed over at https://github.com/knolleary/node-red/tree/subflows - there will be frequent squashing/rebasing/force pushing of the commits over there as I get things in order. Once there are stable cuts, they will be PR'd over into this repo.

Some of the remaining tasks (in no particular order atm):

_Runtime_
- [x] Add runtime support for subflows :exclamation: 

_Misc_
- [x] Icon
- [x] Info Sidebar content
- [x] Prevent adding a subflow node to itself
- [ ] Hover tooltip - do better than 'no information available'
- [x] ? Separate out 'Create subflow' (empty) and 'Create from selection' (existing behaviour)

_History_
- [x] add/remove inputs - update instance nodes to add/remove input port
- [x] create subflow
- [x] wire inputs/outputs
- [x] add/remove outputs

_Menu_
- [x] Add menu option to 'create subflow'
- [x] Disable menu option to rename/delete tab when activeSubflow
- [x] Update menu items when tab/subflow is renamed

_Subflow edit dialog_
- [x] Add delete option to subflow edit dialog
- [x] Display number of instances of a subflow
- [x] How to rename a subflow
- [x] How to add/remove inputs/outputs

_Import/Export_
- [x] Export including a subflow:instance must pull in subflow nodes (recursively...)
- [x] Should lasso/selecting nodes include inputs/outputs.
- [x] How to import/export sensibly?

_Palette_
- [x] Update subflow icon ports on edit
- [x] Handle long subflow name changes

**Comment by mfeblowitz** [comment]
Questions on subflows:
* Is there a way to propagate the status indicator for a nested out node to the parent node?
* Can configuration selections in the subflow's nodes somehow be propagated to the parent node?  
* Is there a means of packaging subflows as reusable nodes?

It seems (and this is ok) like a subflow in the current realization is a means of simplifying flow diagrams. It is also a means of prototyping what might eventually be reimplemented as a wrapper node, for reuse, unless there is a way to treat the node for a subflow as a proper node.

**Comment by knolleary** [comment]
Hi @mfeblowitz - in general, as this item is closed, you can use the mailing list for general questions.

The current subflow functionality is just the first pass. There are a number of enhancements we're thinking about, some of which have issues raised on this list.

 - status indicators cannot be propagated up
 - can you describe what you mean a bit more on this? We've certainly had thoughts around being able to customise individual instances of a subflow - for example, a subflow that includes an mqtt node, that allows you to set the topic on a per-instance basis.
 - you can export/import the subflow node just as you can any flow. But there isn't any sense of being able to package it and redistribute it as a node.
