### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#566]
We haven't decided on what time-scale we want to enable node-red to be internationalized, but it is something we need to have a plan for.

This needs a high-level design that considers how each of the main components will have to be changed to support i18n. The runtime and editor should be fairly straightforward to add support for message catalogues. The hard part is how nodes can provide localized versions; their current architecture doesn't make it entirely obvious how this will be achieved easily.

Then there is the question of what library to use. Amongst the libraries that appear to be candidates are:
 - [jquery.i18n](https://github.com/wikimedia/jquery.i18n)
 - [i18next](http://i18next.com/)

**Comment by kallenboone** [comment]
The nodes pose an interesting problem for localization. Much of the text associated with them is in an .html file. From what I understand of the editor code (correct me if I'm wrong), the contents of these .html files are appended to the DOM and data-template-name and data-help-name script elements are used to fill the node config dialog and node help panel, respectively. Currently the contents of the the script elements seem to be used without any processing. 

My first thought is to run the markup from these two elements through a basic template engine. All it really needs is a simple find/replace. Both libraries you mentioned allow for specifying an element's PII key using a data-i18n attribute, but that feature doesn't seem to work with nested HTML, which could be a problem since I see a lot of the <label> elements including an <i class="fa fa-user"></i> tag in addition the text. Doing the swapping once the HTML has been added to the DOM could be unnecessarily complicated, as well. 

We could also do the text swapping on the server side. The backend service GET /nodes that returns the node configs would then just do a global find/replace on the html as plaintext, and we can avoid messing with DOM operations outright. Add some caching and I imagine this approach would have better performance than doing the locale swapping on the client side. 

In either case, each .html file would need to replace the text snippets with variables. If we set up our variables like ${key}, then we could use a function like 

nodeHelpText.replace(/\${([a-zA-Z]*)}/g, function(match, key){ return i18n.t(key); });

to perform the replacements. We'd also need a way to specify which PII file to pull the data from. I imagine the core nodes would all use a common file, but additional packages like the web nodes and user nodes would need their own PII file. The client-side approach would make specifying the file easy: just use a property on the object passed to the RED.nodes.registerType() function called in the .html file to set the PII file. I'll have to look more at how the backend stores node information before I determine a good way to specify the PII file with that approach. 

These are my initial thoughts. Let me know what you think and whether you have any questions.

**Comment by knolleary** [comment]
Thanks @kallenboone - that's helpful. I'm going to have a play with i18next and node-i18n this weekend to get a better feel for how they work.

**Comment by dceejay** [comment]
For low power devices like Pi, the more that can be done client side the better. Or have a passthru non translated mode of operation.

**Comment by vergissberlin** [comment]
An important aspect for me is the **translation UI**. It allows to keep track of and maintain the highest possible number of translations.

1. I like the *translate ui* tool from i18next. http://i18next.com/pages/ext_webtranslate.html But it seems a bit too rudimentary.
- **[Pootle](http://translate.sourceforge.net/wiki/)** is a very common tool and is bettor for a higher count of translations keys. Example: http://translation.typo3.org/
- [Here](http://stackoverflow.com/questions/280260/i18n-best-practices-for-internationalization-xliff-gettext-ini) is another or editor which also support **XLIFF** format but it is written in phyton.

**Comment by drwoods** [comment]
The i18next and i18next-client look like good options.  I'm not as worried about UI based tooling, but it does seem to have an option for that along with the i18next-parser extension to bulk pull strings from the code (which could also be used to fail builds if new hard-coded strings are being added.)

@kallenboone  can you post an example of how we would translate an existing core Node (like HTTP in/out or HTTP request) as a fork and maybe a short diff?
Also, how would builds and runtime behave if not all of the code in a project (like node-red-web-nodes) is translated to additional languages?
Would also like to think of how we would denote translated support on the Node-RED Flows site and the core Nodes readme file in an automated fashion.

**Comment by kallenboone** [comment]
@drwoods Good questions. I'm working on the fork/diff currently, and I should have something to show in the next day or so. 
Ideally, the code would fallback to English (or whatever original language) when a translation is not available. The i18next library supports the fallback functionality. Third party node developers would also likely have the ability to just hardcode their text instead of providing a PII file. How these things pan out in practice will depend on our implementation, of course. 
How we would denote translation support also depends on our implementation. The simplest way would be to include a flag in the node's config object in the .html file. We'll likely need some sort of option there to point to the PII directory anyway.

**Comment by knolleary** [comment]
@kallenboone as I said on the call today, please can you and I sit down to design this before you get too involved in code. There are fundamental architectural issues to address that we need to work together on.

**Comment by kallenboone** [comment]
@knolleary No prob. I'm available most of tomorrow afternoon for a meeting. Just let me know when is best for you. The fork I'm working on is just a quick proof of concept, nothing that would likely end up in the final code. It's just an example that we can look at as we work through the architecture issues.

**Comment by knolleary** [comment]
Having looked at [i18next](http://i18next.com/), it claims to provide both node.js and browser i18n support, which many of the others don't - they tend to be one or the other.

However, I'm struggling to figure out what version of what library we actually want.

From their home page, they have download links to a v1.8.0 zip file.

They also link to the [i18next-client](https://www.npmjs.com/package/i18next-client) npm package, which is currently v1.8.2 (1 month old). Its README says they are currently looking for contributors for the project - not always a good sign of its long-term prospects.

The page also links to the [i18next](https://www.npmjs.com/package/i18next) npm package, which is currently v1.7.10 (2 months old).

This latter one is intended to run within node.js and iincludes a helper function to serve the library to the browser. Unfortunately, the route it uses to serve the library is hardcoded - not suited for embedding in node-red as is - but certainly something we can work around.

**Comment by knolleary** [comment]
Some more adventures in i18next land. I think I've waded through the various versions. The current plan is:
 - add i18next to our package.json dependency list
 - add the i18next.min.js file from i18next-client to editor/vendor/...
(although, as per @kallenboone first comment, jury is still out on how much we do client side versus server side)

i18next is designed to exist as a singleton - which means we cannot have each node trying to do its own thing and calling `i18next.init` for itself - see [this open issue](https://github.com/i18next/i18next-node/issues/181) for details.

The plan will be to provide a `RED.i18n` api that nodes can use, which provides a shim between the nodes and any particular i18n library - enables us to change the library in the future if needed. What that API looks like is TBD, but will at the very least provide a `RED.i18n._("msg.key")` type function for doing the lookup/replace of a value.

The next hurdle is that i18next expects to find all resource files under a common directory structure - the one identified in the single call to `.init` you can make. The solution will be for us to use our own file loading backend to i18next that maintains a map of namespace (ie node-type/module name) to locale directory. Nodes either then explicitly register or we dynamically discover the appropriate locale directory for them - still need to design what that looks like.

**Comment by drwoods** [comment]
@knolleary Creating a `RED.i18n` wrapper and file loader sounds good...

**Comment by knolleary** [comment]
Right, have pushed some initial thoughts to the new i18n branch: https://github.com/node-red/node-red/tree/i18n

This does the following:

 - adds i18next to package.json
 - adds i18next.min.js to the vendor js collection
 - adds `red/i18n.js`
 - adds `locales/en-US/messages.json` as a starting point for pulling runtime messages into
 - extracted all messages from `red/server.js` to see how it works in practice.

`red/i18n` is where the action is. It provides three functions (so far):

 - `i18n.init` - does the initialisation of the underlying library. This is called by `red/server.js` - no need to be called by anyone else.
 - `i18n.registerMessageCatalog(namespace,dir)` - a function that (when exposed properly) can be called by (or on behalf of) nodes when they register themselves in order to register their message catalog location.
 - `i18n._(key,options)` - the function to look-up a message from the catalogs.

The basic premise is that core runtime stuff will be in the default `messages` namespace. This namespace is implicit if the `key` doesn't explicitly identify one. A node that has registered under the `foo` namespace would use keys of the format `foo:my-message-key`.

Next steps:

 - [ ] add `i18n` module to the `red/red.js` interface for nodes to use
 - [ ] think about how a node module can contribute its own message file - should it be an explicit action, or implicit by the existence of a `locales` directory and a sensible convention for namespace to use.
 - [ ] think about how node-help should be handled - that's a large body of text, not a short message to swap in at runtime. Something along the lines of pulling out node help into its own file (rather than in the current .html files) - then have locale-specific versions of that file that can be loaded on demand by the editor. But all done in a backwards compatible way (of course).
 - [ ] look at how the editor-side of things would work
    - [ ] how are messages loaded into the editor (where are the routes set up?)
    - [ ] add `RED.i18n` equivalent wrapper for the editor side of things

**Comment by knolleary** [comment]
Starting to document what is done here: https://github.com/node-red/node-red/wiki/Design:-i18n

**Comment by kallenboone** [comment]
I have some sample changes to the editor on my fork: https://github.com/kallenboone/node-red

Currently only the dropdown menu in the top right corner of the editor is translated. Most of the code for that change is in `node-red/editor/js/main.js`. However, there are two pieces of it that require some manual work. First, the translations folder under the editor directory needs to be copied to the public folder after building Node Red. I'm working on updating the grunt file to automate this task. 

The second and more pressing issue is that the locale is currently hardcoded into the editor. If you want to change the locale you'll need to change the code in `main.js` where the i18n module is initialized. Exposing the user's locale to the client side code is tricky since the browser does not make this information available in a meaningful way. It's further complicated by inconsistencies across browsers. The typical approach is to obtain the locale from the `Accept-Language` header on the server side and insert it into the client side code using a template, but currently all the editor client-side code seems to be served statically. I'm looking at options for exposing the locale in a way that we can use.

**Comment by knolleary** [comment]
@kallenboone thanks for that.

The work I've been doing in my fork deals with how the nls files can be loaded into the editor in a consistent way. Let me finish that off and we can see how it plugs into your updates. No need for the grunt changes then.

I think the question of how the editor asserts what language it wants is a good one to investigate - not looked at that yet. Based on my work mentioned above, I was thinking that the editor should just load its message catalog with no reference to language in the url - the server then detects and serves the appropriate catalog. This will need a slightly different approach to initialising i18n - giving it a preloaded catalog rather than getting it to load it dynamically. This would also extend to the node catalogs.

If you can dig some more into how other apps do language detection that would be good - I'd like to avoid an explicit language selector in the UI if we can avoid it.

**Comment by knolleary** [comment]
I've updated my branch and I think it now provides most the infrastructure and capability needed for this issue. It enables nls of core runtime content, editor content and node-specific content (both in runtime and editor). Details on the wiki page here: https://github.com/node-red/node-red/wiki/Design:-i18n

I have also updated the Inject node to extract its strings. This is the starting point for updating the other core nodes.

It still assumes `en-US` for language - need to figure out how best to determine language on the server side and pass it through.

@kallenboone please can you start basing your changes from this branch? It will need a little rework of the menu changes you did, but the essentials are there.

**Comment by kallenboone** [comment]
I implemented locale switching based on the `Accept-Language` header in the exposelocale branch of my fork: https://github.com/kallenboone/node-red/tree/exposelocale

I added a helper function, `determineLangFromHeaders()`, to `red/i18n.js`. It takes the `Accept-Language` header (obtained from `req.acceptedLanguages`) and parses it to determine which language from our list of supported languages to use. The `GET locales` REST API leverages this function to serve the proper language. Also, the `red/i18n.js` module now pre-loads our supported languages in the module's `init()` function. 

Some odds and ends:
* Because the locale is determined from the the `Accept-Language` header, the `lang` query parameter passed in to the `GET locales` REST call is not used. 
* I generated pseudo-string PII files in the zz-ZZ locale to test locale switching. Having an extra locale also helps with spotting hardcoded strings that didn't get converted to use the i18n library. 
* The current implementation properly exposes the locale for code in the editor and the nodes' HTML files. The nodes' JS files, however, are still defaulting to English. I'm looking into the issue. 

Let me know if you have any questions, concerns, comments, recommendations, etc.

**Comment by knolleary** [comment]
Sounds good, will look properly tomorrow.

As for the node js files... They are part of the runtime, so should pickup
the runtime locale (presumably through the LOCALE env var, or similar), not
the locale being requested by the editor.

I don't think we should preload anything other than en-US. We are, by
default, a single user system - loading multiple languages is a waste of
resource.

**Comment by kallenboone** [comment]
I removed the preloading. Instead now it only loads a language when it's requested, but that language is still cached due to the implementation of the `MessageFileLoader` in `red/i18n.js`. 

I hadn't considered the runtime having a separate locale from the editor. Determining the system locale may be tricky (Windows at least doesn't surface it through an environment varaible), but I found a [library that may help](https://github.com/sindresorhus/os-locale). I'll investigate a bit further tomorrow. 

Most of the runtime strings are just log messages, but some of them are surfaced to the editor in the node js files. Typically this is done through the `Node.prototype.status()` method. Using the editor locale isn't practical here since it's using a websocket instead of HTTP to transfer the headers. We could send a key to be translated on the client side, though.

**Comment by kallenboone** [comment]
I pushed my work on the palette categories to a new branch on my fork. You can view my changes in [the commit there](https://github.com/kallenboone/node-red/commit/e74ee6d81f32ce30cf7637c5ccaa87fe219fb1ba). 

I changed the `createCategoryContainer` function to optionally accept a `label` as its second parameter. If `label` isn't provided it defaults to using `category` as before. The `init` function now passes in the translated label by calling `RED._("palette.core."+category)`. 

I wasn't sure how to handle the case with categories pulled from `RED.settings.paletteCategories`. I set up some quick code to look for `RED.settings.paletteCategoryLabels` and use those as keys for the categories or else fall back on the labels, then the category names. However, I couldn't get that property to surface through `RED.settings` for some reason. I'll have to follow the path on how settings are exposed to modules, but before I do that I'd like to hear your input on this approach. 

Similarly, I haven't yet implemented NLS for categories added outside of the `core` categories. I wanted to hear your input before I work through the code path of adding a new category through a node.

**Comment by dceejay** [comment]
just fyi - Nick is on a short vacation until Monday.

**Comment by knolleary** [comment]
@dceejay I am... but I was knew this was arriving to be looked at...

@kallenboone ok on the approach for the core categories, but not sure about the paletteCategoryLabels approach. Not clear to me how a user would provide their own message catalog for the custom categories added there - I'm not convinced that's an edge case worth solving at the moment.

For nodes that specify non-core categories, we could adopt a convention that the node should provide a message with key of `palette.label.[category]` and the palette code would go find that in the right namespace - if it wanted a custom label.

From the call earlier, if/when you make progress on this, please post a comment here outlining what area you're looking at next. I need to do a massive rebase of the i18n branch to get it up to date with master - but doing so will break your fork (...detached heads...). I'm also going to go through and do an en masse tidy up of a few things now we have most of the code nls'd - but again, need to know what you're looking at as I don't want to duplicate effort or overlap.

As @dceejay says, I'm out the next couple days - but may have some bandwidth on Friday evening.

**Comment by kallenboone** [comment]
I'm still working on the palette code with the node custom categories. However, I believe that this is the last bit of editor text without NLS enablement. Once it's done I can help out with other aspects of i18n. Do you have anything in particular in mind?

**Comment by knolleary** [comment]
Once your stuff is in and I can rebase to master, will do a complete review
of where its at.

One piece still to do that I don't know if anyone picked up is nlsing the
swagger node. Don't know if Scott or Cody planned on doing that.

**Comment by scott1y** [comment]
Hi Nick, Allen, Cody,
I will work NLS for the swagger node.

**Comment by kallenboone** [comment]
I've been working on NLSing the categories for custom nodes, and I have the basic implementation in the i18n branch on my fork. However, I have not been able to test it since I haven't been able to surface the NLS files from custom nodes. Is the NLS-enablement for custom nodes implemented? I tried creating my own basic node and putting it in the nodes directory, but its module always shows up as `node-red`, and so it looks at the core nodes' locale files. I also tried it with an NPM-installed web-node. I created a locale directory in the node's installation folder, but the contents aren't being loaded. The calls to the backend return an empty JSON object. 

If it hasn't been implemented or if it isn't a known problem that someone is looking into, I can continue working on getting custom node's NLS-enabled since I have the cycles to spare. Let me know how you'd like me to proceed.

**Comment by knolleary** [comment]
@kallenboone what exact file layout did you try when you added the locale file to the npm module? I'm getting on a 12 hour flight shortly, so can't look at it right now. I believe it should work if you follow what was done with the web nodes by @scott1y (although I haven't got his PR merged yet... getting there).

**Comment by scott1y** [comment]
I worked for core nodes, node-red-web-nodes and node-red-node-swagger.  messages.json file is located /git/node-red/nodes/core/locales/en-US for core nodes.  This one file is shared by all core nodes under /git/node-red/nodes/core.  For node-red-web-nodes, these nodes are npm installed to .node-red/node_modules (node-red user directory) separately.  Then, NLS file will be located for each modules under /locales/en-US.  For example, box has .node-red/node_modules/node-red-node-box/locales/en-US/box.json.  swagger node is also npm installed to node-red user directory but one layer below.  So, it is .node-red/node_modules/node-red-node-swagger/swagger/locales/en-US/swagger.json.

**Comment by kallenboone** [comment]
Thanks for the help. I thought I had the layout correct, but it was just slightly off thanks to a typo. I fixed the problem and submitted a PR.

**Comment by kallenboone** [comment]
@knolleary I noticed while testing that the node-help blocks in the nodes' HTML files are not NLS-enabled. We had talked previously about separating them out into their own files and having the editor load the help file for the proper locale. Is that still the plan?

**Comment by knolleary** [comment]
I would like the en-US version to stay in the file as it is, and just have
the other locales separated out. That reduces the overhead of adding yet
another file for every node when running in our default locale.
