### ISSUE TITLE
Credential handling improvements

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#93]
Having updated the MySQL and mqtt nodes to make proper use of the credentials file, there are some improvements to be made.
#222 added the basic framework for this.

There are some remaining tasks:
- [x] document the api and its use

---
- [x] Server-side registration of credentials is currently done via `RED.nodes.registerCredentials` - it should be `RED.credentials.register` (a bug I didn't spot before merging #222 - my fault) (delivered by @Belphemur in #228)
- [x] credential validation - as with properties in the defaults array, it should be possible to specify 'required' or 'validate' properties.  (delivered by @Belphemur in #228)
- [x] save on Deploy - only save credentials on Deploy (as other configuration variable) - and allow Undo in same manner (delivered by @Belphemur  in #251)
- [x] Now I can see it in action, the API we provide for a node to register its credentials (`RED.credentials.register`) doesn't quite feel right. In hindsight, we should move this to be part of `RED.nodes.registerType`. This should also incorporate what is done with `RED.library.registry` so there is one function for registering everything in a single call (although doesn't need to be done up front...) (a6a0352b7027c9fbf63a50b1d4b8297da3ab5e33)
- [x] `RED.nodes.createNode` should prepopulate the node object with a credentials object containing its values. This removes the need for every node implementation to go get the credentials themselves. This will allow us to remove `RED.getCredentials` from the external API. (aa35484a301ad5b6f1f2611dd428d1ee08719179)
- [x] We need a mechanism for a node to take some custom action using the credentials when displaying the edit dialog. `http request` is a good example of a node that wants to use this new api. It needs to toggle the visible state of the authentication fields depending if they are set or not. Currently `oneditprepare` is called asynchronously to the credential-loading request - which means this isn't possible. (b604db83f6b57ee6fef5889ac288d197f9bc4dc3 - oneditprepare is now called after creds have been loaded - `node.credentials` contains them.)
- [x] how to handle email nodes use of including non-credential flag in its http request to indicate if external creds are being used. (made the global flag a credential... problem solved: 8ddfa9eb29de41757d7e7e4ff1b4281f75e1b418)
- [x] decide whether `RED.getCredentials`, `RED.addCredentials` and `RED.deleteCredentials` should be removed from the external API. This can only be done once all existing users are migrated to the new API. (The twitter node is an example of out-of-stream credential handling due to oauth workflow that requires these apis - leave them in place)
